# Generated by Django 5.1.15 on 2026-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("path", models.CharField(default="/", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("dir", "Dir"), ("file", "File")],
                        default="dir",
                        max_length=4,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("tstart_tt", models.FloatField(blank=True, null=True)),
                ("tstop_tt", models.FloatField(blank=True, null=True)),
                ("ra", models.FloatField(blank=True, null=True)),
                ("dec", models.FloatField(blank=True, null=True)),
                ("ndets_used", models.FloatField(blank=True, null=True)),
                ("ushoot_net_rate", models.FloatField(blank=True, null=True)),
                ("oshoot_net_rate", models.FloatField(blank=True, null=True)),
                ("changegoodx_5_12_rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["path"], name="path_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "path", "type"), name="unique_name_path_type"
                    )
                ],
            },
        ),
    ]
