# Generated by Django 5.2.7 on 2025-11-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='changegoodx_5_12_rate',
            new_name='goodx_5_12_rate',
        ),
    ]
