# Generated by Django 5.2.7 on 2025-11-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0002_rename_changegoodx_5_12_rate_item_goodx_5_12_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='goodx_5_12_rate',
            new_name='goodx_0p5_12_rate',
        ),
    ]
