# Generated by Django 5.2.7 on 2025-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0003_rename_goodx_5_12_rate_item_goodx_0p5_12_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='obsid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
