# Generated by Django 5.2.7 on 2025-11-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0004_item_obsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='obsid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
