# Generated by Django 5.2.7 on 2025-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0005_alter_item_obsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='obsid',
            new_name='obs_id',
        ),
        migrations.AddField(
            model_name='item',
            name='gti',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
