# Generated by Django 5.2.7 on 2025-12-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0006_rename_obsid_item_obs_id_item_gti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='goodx_0p5_12_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gti',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ndets_used',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='obs_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='oshoot_net_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tstart_tt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tstop_tt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ushoot_net_rate',
            field=models.FloatField(null=True),
        ),
    ]
