# Generated by Django 5.2.7 on 2025-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0007_alter_item_dec_alter_item_goodx_0p5_12_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file_type',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
