# Generated by Django 5.2.7 on 2025-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0008_item_file_type_item_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
