# Generated by Django 5.2.7 on 2025-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0009_alter_item_file_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['obs_id'], name='obs_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['source'], name='source_idx'),
        ),
    ]
