# Generated by Django 4.1.13 on 2024-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0026_remove_item_type_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
