# Generated by Django 4.1.1 on 2024-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0027_item_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='source_name',
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
