# Generated by Django 4.1.13 on 2024-09-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0028_remove_item_source_name_item_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tstart_tt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tstop_tt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
