# Generated by Django 4.1.13 on 2024-09-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0029_item_dec_item_ra_item_tstart_tt_item_tstop_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='overshoot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='undershoot',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
