# Generated by Django 4.1.13 on 2024-09-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0030_item_overshoot_item_undershoot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='overshoot',
            new_name='ndets_used',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='undershoot',
            new_name='npm_fpm_on',
        ),
        migrations.AddField(
            model_name='item',
            name='detectors_used',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
