# Generated by Django 4.1.13 on 2024-09-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0031_rename_overshoot_item_ndets_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='detectors_used',
        ),
    ]
