# Generated by Django 4.1.13 on 2024-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0032_remove_item_detectors_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='npm_fpm_on',
            new_name='oshoot_net_rate',
        ),
        migrations.AddField(
            model_name='item',
            name='ushoot_net_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
