# Generated by Django 4.1.13 on 2025-01-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_mgr', '0033_rename_npm_fpm_on_item_oshoot_net_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='changegoodx_5_12_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
